#!/bin/bash
# Build viewer: reads inject.js and inject.css, writes viewer-bundle.ts
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
JS_CONTENT=$(cat "$SCRIPT_DIR/viewer/inject.js")
CSS_CONTENT=$(cat "$SCRIPT_DIR/viewer/inject.css" | tr -d '\n' | sed 's/  */ /g')

cat > "$SCRIPT_DIR/backend/src/viewer-bundle.ts" << 'HEADER'
// Auto-generated by build-viewer.sh — do not edit directly
HEADER

echo "export const VIEWER_CSS = \`" >> "$SCRIPT_DIR/backend/src/viewer-bundle.ts"
echo "$CSS_CONTENT" >> "$SCRIPT_DIR/backend/src/viewer-bundle.ts"
echo "\`;" >> "$SCRIPT_DIR/backend/src/viewer-bundle.ts"
echo "" >> "$SCRIPT_DIR/backend/src/viewer-bundle.ts"
echo "export const VIEWER_JS = \`" >> "$SCRIPT_DIR/backend/src/viewer-bundle.ts"
echo "$JS_CONTENT" >> "$SCRIPT_DIR/backend/src/viewer-bundle.ts"
echo "\`;" >> "$SCRIPT_DIR/backend/src/viewer-bundle.ts"

echo "Viewer bundle written to backend/src/viewer-bundle.ts"
